### ISSUE TITLE
Bug which relates to department: null 

### ISSUE THREAD

**Issue by orb1005** [mobileappdevhm/dev-team-1-cie-app-in-flutter#217] opened 2018-06-22 17:11 UTC
Unfortunately, the app still crashes when you didn't specify your department on nine. 
Explanation: 
I fill in my user credentials and click on "LOGIN"
![image](https://user-images.githubusercontent.com/15432349/41789388-681099fc-764f-11e8-912d-3c487a852ae4.png)

After that I land on the timetable page as expected 
![image](https://user-images.githubusercontent.com/15432349/41789475-ba1e7ef8-764f-11e8-9aa5-28c961e2e864.png)

If I then click on courses no courses will be shown 
![image](https://user-images.githubusercontent.com/15432349/41789500-d430a294-764f-11e8-83e1-d2bebd6e3fd2.png)

A click on a different tab throws the error message
![image](https://user-images.githubusercontent.com/15432349/41789532-e9d6fa1c-764f-11e8-9665-a4760b834961.png)

Hope this helps. I assume that some of the other students didn't choose a department so we should fix this as soon as possible.

**Comment by heatsink** [comment] 2018-06-22 21:28
I resolved this in https://github.com/mobileappdevhm/dev-team-1-cie-app-in-flutter/commit/c76f27cf9641806e7d5d64f462bdea109da07a3d

The cause of this is that Nine was returning Fakultät ## instead of just ## for departments, and the dropdown was using this to sort.

Thus the dropdown key was invalid, and the crash occurred. Temporary fix implemented to just trim the string from Nine, I'll implement a better fix later in our user builder so we don't have to worry about it.

**Comment by orb1005** [comment] 2018-06-22 21:55
@heatsink thank you for fixing this so fast

**Comment by jusnelda** [comment] 2018-06-23 15:47
So it's still crashing for me... :-(

**Comment by RedTo** [comment] 2018-06-23 21:10
There is different error if the curriculum returned by nine is null (-> user does not have set any department).

**Comment by RedTo** [comment] 2018-06-23 21:35
Should be fixed with #221. Please check on the corresponding branch, or in master after it is merged and let me know if the problem still occurs on iOS.

I have decided to set the department to an empty string, so we do not need to set an default department. Maybe that is a good approach?!

**Closed by RedTo** 2018-06-23 21:35 UTC
Labels: bug
