### ISSUE TITLE
Filter Cources List

### ISSUE THREAD

**Issue by AndiAndreas** [mobileappdevhm/dev-team-1-cie-app-in-flutter#14] opened 2018-05-21 18:31 UTC
Filter Cources List by passing filter parameters to the presenter.

There is no UI for the filter since yet.

**Comment by heatsink** [comment] 2018-05-28 20:49
Closing, duplicate of the combination of (https://github.com/mobileappdevhm/dev-team-1-cie-app-in-flutter/issues/51, https://github.com/mobileappdevhm/dev-team-1-cie-app-in-flutter/issues/45)

**Closed by heatsink** 2018-05-28 20:49 UTC
